-- ==========================================================
-- VIOTRACK SUPABASE DATABASE SCHEMA & STARTER SEED DATA
-- Run this in your Supabase SQL Editor (supabase.com/dashboard)
-- ==========================================================

-- 1. Enable UUID Extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 2. Drop existing tables if re-initializing (Order matters for Foreign Keys)
DROP TABLE IF EXISTS sms_logs CASCADE;
DROP TABLE IF EXISTS meetings CASCADE;
DROP TABLE IF EXISTS activity_logs CASCADE;
DROP TABLE IF EXISTS records CASCADE;
DROP TABLE IF EXISTS advisers CASCADE;
DROP TABLE IF EXISTS violations CASCADE;
DROP TABLE IF EXISTS teachers CASCADE;
DROP TABLE IF EXISTS admins CASCADE;
DROP TABLE IF EXISTS students CASCADE;

-- ==========================================================
-- 3. CREATE TABLES
-- ==========================================================

-- STUDENTS TABLE
CREATE TABLE students (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lrn VARCHAR(50) UNIQUE NOT NULL,
    fname VARCHAR(100) NOT NULL,
    mname VARCHAR(100) DEFAULT '',
    lname VARCHAR(100) NOT NULL,
    grade VARCHAR(20) NOT NULL,
    section VARCHAR(50) NOT NULL,
    academicyear VARCHAR(20) DEFAULT '2025-2026',
    gender VARCHAR(10) DEFAULT 'Male',
    contact VARCHAR(30) DEFAULT '',
    parent_name VARCHAR(150) DEFAULT '',
    parent_contact VARCHAR(30) DEFAULT '',
    address TEXT DEFAULT '',
    image TEXT DEFAULT '',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ADMINS TABLE
CREATE TABLE admins (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fname VARCHAR(100) NOT NULL,
    lname VARCHAR(100) NOT NULL,
    email VARCHAR(150) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(50) DEFAULT 'admin',
    image TEXT DEFAULT '',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- TEACHERS TABLE
CREATE TABLE teachers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fname VARCHAR(100) NOT NULL,
    lname VARCHAR(100) NOT NULL,
    email VARCHAR(150) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    position VARCHAR(100) DEFAULT 'Teacher I',
    department VARCHAR(100) DEFAULT 'Junior High School',
    contact VARCHAR(30) DEFAULT '',
    image TEXT DEFAULT '',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ADVISERS (Teacher Section Assignments)
CREATE TABLE advisers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    teacher_id BIGINT REFERENCES teachers(id) ON DELETE CASCADE,
    grade_level VARCHAR(20) NOT NULL,
    class_section VARCHAR(50) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(grade_level, class_section)
);

-- VIOLATION CATEGORIES & TYPES
CREATE TABLE violations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(150) NOT NULL,
    description TEXT,
    type VARCHAR(30) NOT NULL CHECK (type IN ('Minor', 'Major')),
    default_sanction TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- VIOLATION RECORDS (Incident Logs)
CREATE TABLE records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT REFERENCES students(id) ON DELETE CASCADE,
    violation_id BIGINT REFERENCES violations(id) ON DELETE SET NULL,
    reported_by_id BIGINT,
    reported_by_type VARCHAR(20) DEFAULT 'admin', -- 'admin' or 'teacher'
    reported_by_name VARCHAR(150),
    date_reported TIMESTAMPTZ DEFAULT NOW(),
    status VARCHAR(30) DEFAULT 'Pending' CHECK (status IN ('Pending', 'Investigation', 'Resolved', 'Dismissed')),
    sanction TEXT DEFAULT '',
    remarks TEXT DEFAULT '',
    resolution_notes TEXT DEFAULT '',
    resolution_date TIMESTAMPTZ,
    sms_notified BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ACTIVITY / AUDIT LOGS
CREATE TABLE activity_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_name VARCHAR(150) NOT NULL,
    user_role VARCHAR(50) NOT NULL,
    action VARCHAR(100) NOT NULL,
    details TEXT,
    ip_address VARCHAR(50) DEFAULT '127.0.0.1',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- PARENT-TEACHER MEETINGS
CREATE TABLE meetings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    record_id BIGINT REFERENCES records(id) ON DELETE CASCADE,
    student_id BIGINT REFERENCES students(id) ON DELETE CASCADE,
    parent_name VARCHAR(150) NOT NULL,
    meeting_date DATE NOT NULL,
    meeting_time TIME NOT NULL,
    status VARCHAR(30) DEFAULT 'Scheduled' CHECK (status IN ('Scheduled', 'Completed', 'Cancelled', 'No Show')),
    notes TEXT DEFAULT '',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- SMS NOTIFICATION LOGS
CREATE TABLE sms_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT REFERENCES students(id) ON DELETE CASCADE,
    record_id BIGINT REFERENCES records(id) ON DELETE SET NULL,
    recipient_name VARCHAR(150),
    phone_number VARCHAR(30) NOT NULL,
    message TEXT NOT NULL,
    status VARCHAR(20) DEFAULT 'Sent',
    sent_at TIMESTAMPTZ DEFAULT NOW()
);

-- ==========================================================
-- 4. ROW LEVEL SECURITY (RLS) POLICIES
-- ==========================================================
ALTER TABLE students ENABLE ROW LEVEL SECURITY;
ALTER TABLE admins ENABLE ROW LEVEL SECURITY;
ALTER TABLE teachers ENABLE ROW LEVEL SECURITY;
ALTER TABLE advisers ENABLE ROW LEVEL SECURITY;
ALTER TABLE violations ENABLE ROW LEVEL SECURITY;
ALTER TABLE records ENABLE ROW LEVEL SECURITY;
ALTER TABLE activity_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE meetings ENABLE ROW LEVEL SECURITY;
ALTER TABLE sms_logs ENABLE ROW LEVEL SECURITY;

-- Allow read and write for authenticated users and anon clients (Public for prototype or restricted by role)
CREATE POLICY "Public Read Access" ON students FOR ALL USING (true);
CREATE POLICY "Public Read Access" ON admins FOR ALL USING (true);
CREATE POLICY "Public Read Access" ON teachers FOR ALL USING (true);
CREATE POLICY "Public Read Access" ON advisers FOR ALL USING (true);
CREATE POLICY "Public Read Access" ON violations FOR ALL USING (true);
CREATE POLICY "Public Read Access" ON records FOR ALL USING (true);
CREATE POLICY "Public Read Access" ON activity_logs FOR ALL USING (true);
CREATE POLICY "Public Read Access" ON meetings FOR ALL USING (true);
CREATE POLICY "Public Read Access" ON sms_logs FOR ALL USING (true);

-- ==========================================================
-- 5. INITIAL SEED DATA
-- ==========================================================

-- Sample Admins
INSERT INTO admins (fname, lname, email, password, role) VALUES
('System', 'Admin', 'admin@viotrack.edu', 'admin123', 'admin'),
('Maria', 'Santos', 'maria.santos@viotrack.edu', 'admin123', 'admin');

-- Sample Teachers
INSERT INTO teachers (fname, lname, email, password, position, department, contact) VALUES
('Juan', 'Dela Cruz', 'juan.delacruz@viotrack.edu', 'teacher123', 'Master Teacher I', 'Science Department', '09171234567'),
('Elena', 'Reyes', 'elena.reyes@viotrack.edu', 'teacher123', 'Teacher III', 'Mathematics Department', '09181234568'),
('Roberto', 'Aquino', 'roberto.aquino@viotrack.edu', 'teacher123', 'Teacher II', 'English Department', '09191234569');

-- Sample Advisers
INSERT INTO advisers (teacher_id, grade_level, class_section) VALUES
(1, 'Grade 10', 'Rizal'),
(2, 'Grade 10', 'Bonifacio'),
(3, 'Grade 11', 'STEM A');

-- Sample Violation Definitions
INSERT INTO violations (title, description, type, default_sanction) VALUES
('Improper Uniform / Haircut', 'Failure to wear standard school uniform or comply with groom policy', 'Minor', 'Verbal Warning / Written Promise'),
('Tardiness / Class Cutting', 'Unexcused late arrival or skipping class periods without authorization', 'Minor', '1 Hour School Community Service'),
('Use of Mobile Device During Class', 'Unauthorized phone/tablet usage during instruction hours', 'Minor', 'Device confiscation until dismissal'),
('Bullying / Harassment', 'Physical, verbal, or cyber bullying towards peers or staff', 'Major', '3-Day Suspension & Parent Conference'),
('Vandalism / Property Damage', 'Defacing school property, walls, or laboratory equipment', 'Major', 'Property Repair Restitution & Suspension'),
('Possession of Prohibited Items', 'Bringing unauthorized harmful or prohibited items to school grounds', 'Major', 'Parent Conference & Guidance Counseling'),
('Cheating / Academic Dishonesty', 'Copying during examinations or submitting plagiarized works', 'Major', 'Zero on exam & Parent Notification');

-- Sample Students
INSERT INTO students (lrn, fname, mname, lname, grade, section, academicyear, gender, contact, parent_name, parent_contact, address) VALUES
('109283746101', 'Alexander', 'Cruz', 'Mendoza', 'Grade 10', 'Rizal', '2025-2026', 'Male', '09151112233', 'Carlos Mendoza', '09151112234', '124 Rizal St, Sampaloc, Manila'),
('109283746102', 'Sophia', 'Grace', 'Villanueva', 'Grade 10', 'Rizal', '2025-2026', 'Female', '09152223344', 'Lorena Villanueva', '09152223345', '45 Mabini Ave, Quezon City'),
('109283746103', 'Gabriel', 'Luis', 'Torres', 'Grade 10', 'Bonifacio', '2025-2026', 'Male', '09153334455', 'Ramon Torres', '09153334456', '88 Aurora Blvd, San Juan'),
('109283746104', 'Isabella', 'Marie', 'Ramos', 'Grade 11', 'STEM A', '2025-2026', 'Female', '09154445566', 'Patricia Ramos', '09154445567', '73 Commonwealth Ave, QC'),
('109283746105', 'Christian', 'Paul', 'Navarro', 'Grade 11', 'STEM A', '2025-2026', 'Male', '09155556677', 'Dennis Navarro', '09155556678', '19 Espana Blvd, Manila'),
('109283746106', 'Jasmine', 'Rose', 'Castillo', 'Grade 9', 'Diamond', '2025-2026', 'Female', '09156667788', 'Lita Castillo', '09156667789', '210 Taft Avenue, Pasay');

-- Sample Violation Records
INSERT INTO records (student_id, violation_id, reported_by_type, reported_by_name, date_reported, status, sanction, remarks, resolution_notes, sms_notified) VALUES
(1, 1, 'teacher', 'Juan Dela Cruz', NOW() - INTERVAL '2 days', 'Resolved', 'Verbal Warning', 'Forgot school necktie and ID lace.', 'Student complied the following day and was cleared.', TRUE),
(1, 2, 'admin', 'System Admin', NOW() - INTERVAL '5 hours', 'Pending', '1 Hour Community Service', 'Arrived 40 minutes late without excuse slip.', '', TRUE),
(3, 4, 'teacher', 'Elena Reyes', NOW() - INTERVAL '1 day', 'Investigation', 'Parent Conference', 'Involved in an altercation in corridor.', 'Scheduled parent discussion on Friday.', TRUE),
(4, 3, 'teacher', 'Roberto Aquino', NOW() - INTERVAL '3 days', 'Resolved', 'Confiscation', 'Playing games during Chemistry lab.', 'Device returned to guardian.', TRUE),
(5, 5, 'admin', 'System Admin', NOW() - INTERVAL '4 days', 'Pending', 'Restitution', 'Graffiti on classroom desk.', '', FALSE);

-- Sample Activity Logs
INSERT INTO activity_logs (user_name, user_role, action, details) VALUES
('System Admin', 'admin', 'Login', 'Admin logged into VioTrack portal'),
('Juan Dela Cruz', 'teacher', 'Add Violation', 'Logged Minor violation for Alexander Mendoza (LRN: 109283746101)'),
('System Admin', 'admin', 'Status Update', 'Marked violation #1 as Resolved'),
('Elena Reyes', 'teacher', 'SMS Alert', 'Sent parent SMS notification to Carlos Mendoza');
