-- ==============================================================================
-- VIOTRACK DISCIPLINARY & STUDENT WELFARE MANAGEMENT SYSTEM
-- COMPLETE DATABASE SCHEMA & BACKUP (PostgreSQL / Supabase Compatible)
-- File: VioTrack.sql
-- Generated: 2026-10-04
-- ==============================================================================

-- 1. EXTENSIONS
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS pg_trgm;

-- 2. DROP TABLES IF RE-INITIALIZING (Preserves Foreign Key Cascade Order)
DROP TABLE IF EXISTS sms_logs CASCADE;
DROP TABLE IF EXISTS meetings CASCADE;
DROP TABLE IF EXISTS activity_logs CASCADE;
DROP TABLE IF EXISTS student_locations CASCADE;
DROP TABLE IF EXISTS school_events CASCADE;
DROP TABLE IF EXISTS records CASCADE;
DROP TABLE IF EXISTS advisers CASCADE;
DROP TABLE IF EXISTS violations CASCADE;
DROP TABLE IF EXISTS teachers CASCADE;
DROP TABLE IF EXISTS admins CASCADE;
DROP TABLE IF EXISTS students CASCADE;

-- ==============================================================================
-- 3. CORE DATABASE TABLES
-- ==============================================================================

-- STUDENTS MASTER TABLE
CREATE TABLE students (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id VARCHAR(50) UNIQUE NOT NULL,
    fname VARCHAR(100) NOT NULL,
    mname VARCHAR(100) DEFAULT '',
    lname VARCHAR(100) NOT NULL,
    email VARCHAR(150) DEFAULT '',
    grade VARCHAR(20) NOT NULL,
    section VARCHAR(50) NOT NULL,
    academicyear VARCHAR(20) DEFAULT '2025-2026',
    gender VARCHAR(10) DEFAULT 'Male',
    contact VARCHAR(30) DEFAULT '',
    parent_name VARCHAR(150) DEFAULT '',
    parent_contact VARCHAR(30) DEFAULT '',
    address TEXT DEFAULT '',
    password VARCHAR(255) DEFAULT 'Viotrack@2026!',
    image TEXT DEFAULT '',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ADMINISTRATORS TABLE
CREATE TABLE admins (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fname VARCHAR(100) NOT NULL,
    mname VARCHAR(100) DEFAULT '',
    lname VARCHAR(100) NOT NULL,
    email VARCHAR(150) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(50) DEFAULT 'Head Admin',
    position VARCHAR(100) DEFAULT 'Discipline Officer',
    image TEXT DEFAULT '',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- TEACHERS / FACULTY TABLE
CREATE TABLE teachers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fname VARCHAR(100) NOT NULL,
    mname VARCHAR(100) DEFAULT '',
    lname VARCHAR(100) NOT NULL,
    email VARCHAR(150) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    position VARCHAR(100) DEFAULT 'Master Teacher I',
    department VARCHAR(100) DEFAULT 'Junior High School',
    contact VARCHAR(30) DEFAULT '',
    gender VARCHAR(10) DEFAULT 'Male',
    image TEXT DEFAULT '',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ADVISERS (Teacher Section Assignment Matrix)
CREATE TABLE advisers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    teacher_id BIGINT REFERENCES teachers(id) ON DELETE CASCADE,
    grade_level VARCHAR(20) NOT NULL,
    class_section VARCHAR(50) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(grade_level, class_section)
);

-- VIOLATIONS CODEBOOK (Student Code of Conduct Infractions)
CREATE TABLE violations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(150) NOT NULL,
    description TEXT,
    type VARCHAR(30) NOT NULL CHECK (type IN ('Minor', 'Major')),
    severity VARCHAR(30) DEFAULT 'Minor',
    default_sanction TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- VIOLATION INCIDENT RECORDS
CREATE TABLE records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT REFERENCES students(id) ON DELETE CASCADE,
    violation_id BIGINT REFERENCES violations(id) ON DELETE SET NULL,
    reported_by_id BIGINT,
    reported_by_type VARCHAR(20) DEFAULT 'admin', -- 'admin' or 'teacher'
    reported_by_name VARCHAR(150),
    date_reported TIMESTAMPTZ DEFAULT NOW(),
    status VARCHAR(30) DEFAULT 'Pending' CHECK (status IN ('Pending', 'Investigation', 'Resolved', 'Dismissed', 'Under Approval', 'Rejected')),
    approval_status VARCHAR(30) DEFAULT 'Approved' CHECK (approval_status IN ('Under Approval', 'Approved', 'Rejected')),
    approved_by VARCHAR(150),
    approved_at TIMESTAMPTZ,
    rejected_by VARCHAR(150),
    rejected_at TIMESTAMPTZ,
    rejection_reason TEXT,
    sanction TEXT DEFAULT '',
    remarks TEXT DEFAULT '',
    resolution_notes TEXT DEFAULT '',
    resolution_date TIMESTAMPTZ,
    sms_notified BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- REAL-TIME CAMPUS STUDENT GEOLOCATION TRACKING
CREATE TABLE student_locations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT REFERENCES students(id) ON DELETE CASCADE,
    latitude DECIMAL(10, 7) NOT NULL,
    longitude DECIMAL(10, 7) NOT NULL,
    location_name VARCHAR(150) NOT NULL,
    status VARCHAR(50) DEFAULT 'In Class',
    timestamp TIMESTAMPTZ DEFAULT NOW(),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- INSTITUTIONAL & CALENDAR EVENTS
CREATE TABLE school_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(150) NOT NULL,
    description TEXT,
    event_date DATE NOT NULL,
    event_time TIME DEFAULT '08:00',
    venue VARCHAR(150) DEFAULT 'Campus Quadrangle',
    event_type VARCHAR(50) DEFAULT 'Academic',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- IMMUTABLE AUDIT TRAIL ACTIVITY LOGS
CREATE TABLE activity_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_name VARCHAR(150) NOT NULL,
    user_role VARCHAR(50) NOT NULL,
    action VARCHAR(100) NOT NULL,
    details TEXT,
    ip_address VARCHAR(50) DEFAULT '127.0.0.1',
    workstation VARCHAR(100) DEFAULT 'Windows PC / Chrome Browser',
    audit_hash VARCHAR(64),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- PARENT-TEACHER & DISCIPLINARY CONFERENCES
CREATE TABLE meetings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    record_id BIGINT REFERENCES records(id) ON DELETE CASCADE,
    student_id BIGINT REFERENCES students(id) ON DELETE CASCADE,
    parent_name VARCHAR(150) NOT NULL,
    meeting_date DATE NOT NULL,
    meeting_time TIME NOT NULL,
    venue VARCHAR(150) DEFAULT 'Prefect of Discipline Office',
    status VARCHAR(30) DEFAULT 'Scheduled' CHECK (status IN ('Scheduled', 'Completed', 'Cancelled', 'No Show')),
    notes TEXT DEFAULT '',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- SMS NOTIFICATION & DISPATCH LOGS
CREATE TABLE sms_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT REFERENCES students(id) ON DELETE CASCADE,
    record_id BIGINT REFERENCES records(id) ON DELETE SET NULL,
    recipient_name VARCHAR(150),
    phone_number VARCHAR(30) NOT NULL,
    message TEXT NOT NULL,
    status VARCHAR(20) DEFAULT 'Sent',
    sent_at TIMESTAMPTZ DEFAULT NOW()
);

-- ==============================================================================
-- 4. HIGH-PERFORMANCE DATABASE INDEXES (Scaled for 50,000+ Students)
-- ==============================================================================

-- Student Lookups & Search
CREATE INDEX IF NOT EXISTS idx_students_student_id ON students(student_id);
CREATE INDEX IF NOT EXISTS idx_students_grade_section ON students(grade, section);
CREATE INDEX IF NOT EXISTS idx_students_academic_year ON students(academicyear);
CREATE INDEX IF NOT EXISTS idx_students_names ON students(lname, fname);
CREATE INDEX IF NOT EXISTS idx_students_name_search ON students USING gin ((fname || ' ' || lname) gin_trgm_ops);

-- Violation Records Indexing
CREATE INDEX IF NOT EXISTS idx_records_student_id ON records(student_id);
CREATE INDEX IF NOT EXISTS idx_records_violation_id ON records(violation_id);
CREATE INDEX IF NOT EXISTS idx_records_status ON records(status);
CREATE INDEX IF NOT EXISTS idx_records_date_reported ON records(date_reported DESC);
CREATE INDEX IF NOT EXISTS idx_records_status_approval ON records(status, approval_status);
CREATE INDEX IF NOT EXISTS idx_records_approval_date ON records(approval_status, date_reported DESC);

-- Faculty & Advisory Matrix
CREATE INDEX IF NOT EXISTS idx_advisers_teacher ON advisers(teacher_id);
CREATE INDEX IF NOT EXISTS idx_advisers_grade_section ON advisers(grade_level, class_section);

-- Real-time Locations & Audit Logs
CREATE INDEX IF NOT EXISTS idx_student_locations_student ON student_locations(student_id);
CREATE INDEX IF NOT EXISTS idx_activity_logs_created ON activity_logs(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_sms_logs_student ON sms_logs(student_id);

-- ==============================================================================
-- 5. ROW LEVEL SECURITY (RLS) POLICIES
-- ==============================================================================

ALTER TABLE students ENABLE ROW LEVEL SECURITY;
ALTER TABLE admins ENABLE ROW LEVEL SECURITY;
ALTER TABLE teachers ENABLE ROW LEVEL SECURITY;
ALTER TABLE advisers ENABLE ROW LEVEL SECURITY;
ALTER TABLE violations ENABLE ROW LEVEL SECURITY;
ALTER TABLE records ENABLE ROW LEVEL SECURITY;
ALTER TABLE student_locations ENABLE ROW LEVEL SECURITY;
ALTER TABLE school_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE activity_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE meetings ENABLE ROW LEVEL SECURITY;
ALTER TABLE sms_logs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public Read/Write Access" ON students FOR ALL USING (true);
CREATE POLICY "Public Read/Write Access" ON admins FOR ALL USING (true);
CREATE POLICY "Public Read/Write Access" ON teachers FOR ALL USING (true);
CREATE POLICY "Public Read/Write Access" ON advisers FOR ALL USING (true);
CREATE POLICY "Public Read/Write Access" ON violations FOR ALL USING (true);
CREATE POLICY "Public Read/Write Access" ON records FOR ALL USING (true);
CREATE POLICY "Public Read/Write Access" ON student_locations FOR ALL USING (true);
CREATE POLICY "Public Read/Write Access" ON school_events FOR ALL USING (true);
CREATE POLICY "Public Read/Write Access" ON activity_logs FOR ALL USING (true);
CREATE POLICY "Public Read/Write Access" ON meetings FOR ALL USING (true);
CREATE POLICY "Public Read/Write Access" ON sms_logs FOR ALL USING (true);

-- ==============================================================================
-- 6. OFFICIAL SEED DATA & INSTITUTIONAL BASELINE
-- ==============================================================================

-- 6.1 Sample Administrators
INSERT INTO admins (fname, mname, lname, email, password, role, position) VALUES
('Sheryl', 'B.', 'Gamboa', 'admin@phcmanila.edu.ph', 'Viotrack@2026!', 'Head Admin', 'Head of Student Affairs'),
('System', '', 'Administrator', 'admin@viotrack.edu', 'admin123', 'System Admin', 'IT & Systems Security Lead'),
('Maria', 'L.', 'Santos', 'maria.santos@viotrack.edu', 'admin123', 'Discipline Officer', 'Guidance & Conduct Officer');

-- 6.2 Sample Teachers
INSERT INTO teachers (fname, mname, lname, email, password, position, department, contact, gender) VALUES
('Juan', 'D.', 'Dela Cruz', 'juan.delacruz@viotrack.edu', 'teacher123', 'Master Teacher I', 'Science Department', '09171234567', 'Male'),
('Elena', 'M.', 'Reyes', 'elena.reyes@viotrack.edu', 'teacher123', 'Teacher III', 'Mathematics Department', '09181234568', 'Female'),
('Roberto', 'C.', 'Aquino', 'roberto.aquino@viotrack.edu', 'teacher123', 'Teacher II', 'English Department', '09191234569', 'Male'),
('Carmela', 'S.', 'Bautista', 'carmela.bautista@viotrack.edu', 'teacher123', 'Teacher I', 'Social Studies Department', '09153334411', 'Female'),
('Fernando', 'T.', 'Perez', 'fernando.perez@viotrack.edu', 'teacher123', 'Senior High Instructor', 'TVL Track', '09154445522', 'Male');

-- 6.3 Sample Class Advisers
INSERT INTO advisers (teacher_id, grade_level, class_section) VALUES
(1, 'Grade 10', 'Rizal'),
(2, 'Grade 10', 'Bonifacio'),
(3, 'Grade 11', 'STEM A'),
(4, 'Grade 9', 'Diamond'),
(5, 'Grade 12', 'ICT 1');

-- 6.4 Official Violation Codebook
INSERT INTO violations (title, description, type, severity, default_sanction) VALUES
('Improper Uniform / Haircut', 'Failure to wear standard school uniform, ID badge, or comply with haircut policy', 'Minor', 'Minor', 'Verbal Warning / Written Promise'),
('Tardiness / Class Cutting', 'Unexcused late arrival or skipping class periods without official pass', 'Minor', 'Minor', '1 Hour Campus Service'),
('Use of Mobile Device During Class', 'Unauthorized phone, tablet, or gaming device usage during instruction hours', 'Minor', 'Minor', 'Device confiscation until dismissal'),
('Littering / Waste Disposal Non-Compliance', 'Improper disposal of trash or food wrappers on campus grounds', 'Minor', 'Minor', 'Campus Beautification Duty'),
('Bullying / Harassment', 'Physical, verbal, psychological, or cyber bullying towards peers or staff', 'Major', 'Major', '3-Day Suspension & Parent Conference'),
('Vandalism / Property Damage', 'Defacing school property, armchairs, walls, or science laboratory equipment', 'Major', 'Major', 'Restitution & Disciplinary Probation'),
('Possession of Prohibited Items', 'Bringing unauthorized harmful items, vape, or contraband to school grounds', 'Major', 'Major', 'Parent Conference & Guidance Referral'),
('Cheating / Academic Dishonesty', 'Copying during examinations, unauthorized notes, or submitting plagiarized outputs', 'Major', 'Major', 'Zero Score & Formal Reprimand'),
('Physical Altercation / Fighting', 'Engaging in violent fights, physical assaults, or instigating brawls', 'Major', 'Major', '5-Day Suspension & Corrective Action Plan');

-- 6.5 Sample Enrolled Students
INSERT INTO students (student_id, fname, mname, lname, grade, section, academicyear, gender, contact, parent_name, parent_contact, address, image) VALUES
('109283746101', 'Alexander', 'Cruz', 'Mendoza', 'Grade 10', 'Rizal', '2025-2026', 'Male', '09151112233', 'Carlos Mendoza', '09151112234', '124 Rizal St, Sampaloc, Manila', 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&auto=format&fit=crop&q=80'),
('109283746102', 'Sophia', 'Grace', 'Villanueva', 'Grade 10', 'Rizal', '2025-2026', 'Female', '09152223344', 'Lorena Villanueva', '09152223345', '45 Mabini Ave, Quezon City', 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80'),
('109283746103', 'Gabriel', 'Luis', 'Torres', 'Grade 10', 'Bonifacio', '2025-2026', 'Male', '09153334455', 'Ramon Torres', '09153334456', '88 Aurora Blvd, San Juan', 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80'),
('109283746104', 'Isabella', 'Marie', 'Ramos', 'Grade 11', 'STEM A', '2025-2026', 'Female', '09154445566', 'Patricia Ramos', '09154445567', '73 Commonwealth Ave, QC', 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80'),
('109283746105', 'Christian', 'Paul', 'Navarro', 'Grade 11', 'STEM A', '2025-2026', 'Male', '09155556677', 'Dennis Navarro', '09155556678', '19 Espana Blvd, Manila', 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80'),
('109283746106', 'Jasmine', 'Rose', 'Castillo', 'Grade 9', 'Diamond', '2025-2026', 'Female', '09156667788', 'Lita Castillo', '09156667789', '210 Taft Avenue, Pasay', 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80');

-- 6.6 Sample Disciplinary Incident Records
INSERT INTO records (student_id, violation_id, reported_by_type, reported_by_name, date_reported, status, approval_status, approved_by, approved_at, sanction, remarks, resolution_notes, sms_notified) VALUES
(1, 1, 'teacher', 'Juan Dela Cruz', NOW() - INTERVAL '2 days', 'Resolved', 'Approved', 'System Admin', NOW() - INTERVAL '2 days', 'Verbal Warning', 'Forgot school necktie and ID badge.', 'Student complied the following day and signed acknowledgment.', TRUE),
(1, 2, 'admin', 'System Admin', NOW() - INTERVAL '5 hours', 'Pending', 'Approved', 'System Admin', NOW() - INTERVAL '5 hours', '1 Hour Campus Service', 'Arrived 40 minutes late without authorized excuse slip.', '', TRUE),
(3, 5, 'teacher', 'Elena Reyes', NOW() - INTERVAL '1 day', 'Investigation', 'Approved', 'System Admin', NOW() - INTERVAL '1 day', 'Parent Conference', 'Involved in a verbal altercation in 2nd floor hallway.', 'Scheduled parent discussion on Friday.', TRUE),
(4, 3, 'teacher', 'Roberto Aquino', NOW() - INTERVAL '3 days', 'Resolved', 'Approved', 'System Admin', NOW() - INTERVAL '3 days', 'Device Confiscation', 'Playing mobile games during Chemistry lab instruction.', 'Device returned to parent upon conference.', TRUE),
(5, 6, 'admin', 'System Admin', NOW() - INTERVAL '4 days', 'Pending', 'Approved', 'System Admin', NOW() - INTERVAL '4 days', 'Desk Restitution', 'Graffiti drawing on classroom desk.', '', FALSE),
(2, 2, 'teacher', 'Elena Reyes', NOW() - INTERVAL '3 hours', 'Under Approval', 'Under Approval', NULL, NULL, 'Pending Admin Review', 'Repeated tardiness in morning homeroom period.', '', FALSE);

-- 6.7 Sample Student Locations (Campus Map)
INSERT INTO student_locations (student_id, latitude, longitude, location_name, status) VALUES
(1, 14.6042, 120.9893, 'Main Building - Room 204', 'In Class'),
(2, 14.6045, 120.9897, 'School Library - 3rd Floor', 'Study Period'),
(3, 14.6039, 120.9889, 'Discipline Office - Admin Bldg', 'Counseling Session'),
(4, 14.6048, 120.9902, 'Science Laboratory 2', 'Lab Activity'),
(5, 14.6035, 120.9885, 'Campus Gymnasium', 'PE Class');

-- 6.8 Sample Institutional Activity & Audit Logs
INSERT INTO activity_logs (user_name, user_role, action, details, ip_address, workstation, audit_hash) VALUES
('System Admin', 'Head Admin', 'Login', 'Administrator logged into VioTrack secure portal', '192.168.1.10', 'Windows 11 / Chrome 124', '7f83b1657ff1fc53b92dc18148a1d65dfc2d4b1fa3d677284addd200126d9069'),
('Juan Dela Cruz', 'Faculty Teacher', 'Add Violation', 'Reported Minor infraction for Alexander Mendoza (ID: 109283746101)', '192.168.1.45', 'Staff Workstation #04', 'b2c92e93b1b9e2815ff8e2a39281a65dfc2d4b1fa3d677284addd200126d9101'),
('System Admin', 'Head Admin', 'Status Update', 'Marked incident record #1 as Resolved following compliance', '192.168.1.10', 'Windows 11 / Chrome 124', 'a89c2e93b1b9e2815ff8e2a39281a65dfc2d4b1fa3d677284addd200126d9202'),
('Elena Reyes', 'Faculty Teacher', 'SMS Notification', 'Dispatched official summons SMS to parent Carlos Mendoza', '192.168.1.52', 'Staff Workstation #12', 'c91e2e93b1b9e2815ff8e2a39281a65dfc2d4b1fa3d677284addd200126d9303');

-- 6.9 Sample School Calendar Events
INSERT INTO school_events (title, description, event_date, event_time, venue, event_type) VALUES
('General Faculty & Discipline Assembly', 'Mandatory orientation on DepEd Order 40 & campus welfare protocol', CURRENT_DATE + INTERVAL '2 days', '08:30', 'University Auditorium', 'Institutional'),
('Quarterly Parent-Teacher Disciplinary Review', 'Formal conference for students with multiple unresolved infraction points', CURRENT_DATE + INTERVAL '5 days', '10:00', 'Prefect Conference Room 204', 'Guidance');

